#!/usr/bin/env bash

install_package() {
  brew cask list $1 > /dev/null 2>&1
  if [ $? -ne 0 ]; then
    brew cask install $1
  else
    echo "cask: ${1} ✓"
  fi
}

brew cask > /dev/null 2>&1
if [ $? -ne 0 ]; then
  echo "Installing cask"
  brew install caskroom/cask/brew-cask
else
  echo "Brew cask found"
fi

install_package chromium
install_package iterm2
install_package firefox
install_package slack
install_package spectacle
install_package textmate
