#!/usr/bin/env bash

install_package() {
  brew cask install $1
}

brew cask > /dev/null 2>&1
if [ $? -ne 0 ]; then
  echo "Installing cask"
  brew install caskroom/cask/brew-cask
else
  echo "Brew cask found"
fi

install_package iterm2
install_package textmate
