#!/usr/bin/env bash

install_package() {
  which $1 > /dev/null
  if [ $? -ne 0 ]; then
    brew install $1
  fi
}

install_package "offlineimap"
install_package "mutt"
install_package "msmtp"
install_package "cowsay"
