#!/usr/bin/env bash

install_package() {
  brew list $1 > /dev/null
  if [ $? -ne 0 ]; then
    brew install $1
  fi
}

# For mutt
install_package "offlineimap"
install_package "msmtp"
install_package "mutt"

install_package "cowsay"
install_package "todo-txt"
install_package "jq"
install_package "ghi"

# chruby
install_package "ruby-install"
install_package "chruby"

install_package "node"
